# Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1={
    "name":['harray','rohan','skillf','subh'],
    "marks":[92,34,24,17],
    "city":['rampur','kolkata','barelly','antartica']
    
}

In [3]:
df=pd.DataFrame(dict1)

In [4]:
df

     name  marks       city
0  harray     92     rampur
1   rohan     34    kolkata
2  skillf     24    barelly
3    subh     17  antartica

In [5]:
ser=pd.Series(np.random.rand(34))

In [6]:
type(ser)

pandas.core.series.Series

In [7]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))

In [8]:
newdf.head()

          0         1         2         3         4
0  0.401190  0.049847  0.689273  0.459255  0.925967
1  0.739994  0.665925  0.080437  0.143889  0.873782
2  0.108196  0.173969  0.949344  0.291107  0.686706
3  0.070031  0.002254  0.624236  0.486904  0.583486
4  0.967489  0.744893  0.764783  0.746854  0.725436

In [9]:
newdf

            0         1         2         3         4
0    0.401190  0.049847  0.689273  0.459255  0.925967
1    0.739994  0.665925  0.080437  0.143889  0.873782
2    0.108196  0.173969  0.949344  0.291107  0.686706
3    0.070031  0.002254  0.624236  0.486904  0.583486
4    0.967489  0.744893  0.764783  0.746854  0.725436
..        ...       ...       ...       ...       ...
329  0.371280  0.772342  0.596947  0.082487  0.552833
330  0.997359  0.436256  0.391025  0.230010  0.522288
331  0.857275  0.167689  0.600161  0.768652  0.081345
332  0.095042  0.794782  0.586758  0.972805  0.019028
333  0.609086  0.562896  0.455689  0.919523  0.615873

[334 rows x 5 columns]

In [10]:
type(newdf)

pandas.core.frame.DataFrame

In [11]:
ser

0     0.648049
1     0.746352
2     0.794692
3     0.812223
4     0.286354
5     0.166061
6     0.060744
7     0.846764
8     0.774905
9     0.350795
10    0.607523
11    0.336081
12    0.360731
13    0.359644
14    0.577664
15    0.056774
16    0.237819
17    0.581428
18    0.477383
19    0.137092
20    0.829622
21    0.211112
22    0.930385
23    0.451720
24    0.851262
25    0.505201
26    0.167885
27    0.160729
28    0.997201
29    0.242038
30    0.744336
31    0.691309
32    0.769315
33    0.553001
dtype: float64

In [12]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [13]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.522710    0.477316    0.517138    0.487982    0.496543
std      0.303322    0.276939    0.286023    0.292370    0.286332
min      0.001913    0.000204    0.011757    0.000498    0.003467
25%      0.252057    0.244890    0.266674    0.225793    0.245788
50%      0.541775    0.472552    0.519278    0.468684    0.499941
75%      0.816137    0.690679    0.759731    0.745546    0.749671
max      0.999919    0.993437    0.999857    0.995966    0.999530

In [14]:
newdf[0][0]='harry'

C:\Users\Anurag\AppData\Local\Temp\ipykernel_12928\4037271884.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0]='harry'
C:\Users\Anurag\AppData\Local\Temp\ipykernel_12928\4037271884.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'harry' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0]='harry'

In [15]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [16]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [17]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [18]:
newdf.to_numpy()

array([['harry', 0.049846784554120394, 0.6892728693959477,
        0.4592549776704863, 0.9259665399121643],
       [0.7399944915479701, 0.6659254450424187, 0.08043685346142682,
        0.1438888846472991, 0.8737818929302201],
       [0.10819573216660427, 0.17396901220121885, 0.9493438781844245,
        0.29110689150843083, 0.6867058997031148],
       ...,
       [0.8572745192243058, 0.1676894206891587, 0.6001610821296631,
        0.7686520377441819, 0.08134456975489746],
       [0.09504151777343905, 0.7947824388714684, 0.5867581377582036,
        0.9728051225440457, 0.019027927583936788],
       [0.609085787564253, 0.5628961049691739, 0.45568864145785515,
        0.9195228973416392, 0.6158728302668328]], dtype=object)

In [19]:
newdf[0][0]=0.3

In [20]:
newdf.head()

          0         1         2         3         4
0       0.3  0.049847  0.689273  0.459255  0.925967
1  0.739994  0.665925  0.080437  0.143889  0.873782
2  0.108196  0.173969  0.949344  0.291107  0.686706
3  0.070031  0.002254  0.624236  0.486904  0.583486
4  0.967489  0.744893  0.764783  0.746854  0.725436

In [21]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [22]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.3,0.739994,0.108196,0.070031,0.967489,0.161596,0.115169,0.715252,0.681171,0.255354,...,0.483591,0.604551,0.229506,0.2021,0.164489,0.37128,0.997359,0.857275,0.095042,0.609086
1,0.049847,0.665925,0.173969,0.002254,0.744893,0.458489,0.159287,0.89862,0.218216,0.993437,...,0.726349,0.591719,0.760461,0.471973,0.155751,0.772342,0.436256,0.167689,0.794782,0.562896
2,0.689273,0.080437,0.949344,0.624236,0.764783,0.734789,0.496454,0.030241,0.293486,0.305269,...,0.522176,0.468075,0.539168,0.943828,0.499823,0.596947,0.391025,0.600161,0.586758,0.455689
3,0.459255,0.143889,0.291107,0.486904,0.746854,0.814874,0.938661,0.467356,0.265088,0.442908,...,0.777662,0.90153,0.308576,0.171434,0.307323,0.082487,0.23001,0.768652,0.972805,0.919523
4,0.925967,0.873782,0.686706,0.583486,0.725436,0.974828,0.062452,0.094838,0.832351,0.971202,...,0.25016,0.397349,0.693495,0.387302,0.028033,0.552833,0.522288,0.081345,0.019028,0.615873

In [23]:
newdf.head()

          0         1         2         3         4
0       0.3  0.049847  0.689273  0.459255  0.925967
1  0.739994  0.665925  0.080437  0.143889  0.873782
2  0.108196  0.173969  0.949344  0.291107  0.686706
3  0.070031  0.002254  0.624236  0.486904  0.583486
4  0.967489  0.744893  0.764783  0.746854  0.725436

In [24]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.609086  0.562896  0.455689  0.919523  0.615873
332  0.095042  0.794782  0.586758  0.972805  0.019028
331  0.857275  0.167689  0.600161  0.768652  0.081345
330  0.997359  0.436256  0.391025  0.230010  0.522288
329   0.37128  0.772342  0.596947  0.082487  0.552833
..        ...       ...       ...       ...       ...
4    0.967489  0.744893  0.764783  0.746854  0.725436
3    0.070031  0.002254  0.624236  0.486904  0.583486
2    0.108196  0.173969  0.949344  0.291107  0.686706
1    0.739994  0.665925  0.080437  0.143889  0.873782
0         0.3  0.049847  0.689273  0.459255  0.925967

[334 rows x 5 columns]

In [26]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.609086  0.562896  0.455689  0.919523  0.615873
332  0.095042  0.794782  0.586758  0.972805  0.019028
331  0.857275  0.167689  0.600161  0.768652  0.081345
330  0.997359  0.436256  0.391025  0.230010  0.522288
329   0.37128  0.772342  0.596947  0.082487  0.552833
..        ...       ...       ...       ...       ...
4    0.967489  0.744893  0.764783  0.746854  0.725436
3    0.070031  0.002254  0.624236  0.486904  0.583486
2    0.108196  0.173969  0.949344  0.291107  0.686706
1    0.739994  0.665925  0.080437  0.143889  0.873782
0         0.3  0.049847  0.689273  0.459255  0.925967

[334 rows x 5 columns]

In [27]:
newdf.head()

          0         1         2         3         4
0       0.3  0.049847  0.689273  0.459255  0.925967
1  0.739994  0.665925  0.080437  0.143889  0.873782
2  0.108196  0.173969  0.949344  0.291107  0.686706
3  0.070031  0.002254  0.624236  0.486904  0.583486
4  0.967489  0.744893  0.764783  0.746854  0.725436

In [28]:
newdf[0]

0           0.3
1      0.739994
2      0.108196
3      0.070031
4      0.967489
         ...
329     0.37128
330    0.997359
331    0.857275
332    0.095042
333    0.609086
Name: 0, Length: 334, dtype: object

In [29]:
type(newdf[0])

pandas.core.series.Series

In [30]:
# View
newdf2=newdf

In [31]:
newdf2[0][0]=234

In [32]:
newdf.head()

          0         1         2         3         4
0       234  0.049847  0.689273  0.459255  0.925967
1  0.739994  0.665925  0.080437  0.143889  0.873782
2  0.108196  0.173969  0.949344  0.291107  0.686706
3  0.070031  0.002254  0.624236  0.486904  0.583486
4  0.967489  0.744893  0.764783  0.746854  0.725436

In [33]:
# copy
newdfc=newdf.copy()

In [34]:
newdfc[0][0]=33434

C:\Users\Anurag\AppData\Local\Temp\ipykernel_12928\1076690295.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdfc[0][0]=33434
C:\Users\Anurag\AppData\Local\Temp\ipykernel_12928\1076690295.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdfc[0][0]=33434

In [35]:
newdf.head()

          0         1         2         3         4
0       234  0.049847  0.689273  0.459255  0.925967
1  0.739994  0.665925  0.080437  0.143889  0.873782
2  0.108196  0.173969  0.949344  0.291107  0.686706
3  0.070031  0.002254  0.624236  0.486904  0.583486
4  0.967489  0.744893  0.764783  0.746854  0.725436

In [37]:
#loc
newdf.loc[0,0]=4545

In [38]:
newdf.head()

          0         1         2         3         4
0      4545  0.049847  0.689273  0.459255  0.925967
1  0.739994  0.665925  0.080437  0.143889  0.873782
2  0.108196  0.173969  0.949344  0.291107  0.686706
3  0.070031  0.002254  0.624236  0.486904  0.583486
4  0.967489  0.744893  0.764783  0.746854  0.725436

In [46]:
newdf.columns=list('ABCDe')

In [40]:
newdf.head(2)

          A         B         C         D         E
0      4545  0.049847  0.689273  0.459255  0.925967
1  0.739994  0.665925  0.080437  0.143889  0.873782

In [41]:
newdf.loc[0,0]=787

In [42]:
newdf.head()

          A         B         C         D         E      0
0      4545  0.049847  0.689273  0.459255  0.925967  787.0
1  0.739994  0.665925  0.080437  0.143889  0.873782    NaN
2  0.108196  0.173969  0.949344  0.291107  0.686706    NaN
3  0.070031  0.002254  0.624236  0.486904  0.583486    NaN
4  0.967489  0.744893  0.764783  0.746854  0.725436    NaN

In [43]:
newdf=newdf.drop(0,axis=1)

In [44]:
newdf.head()

          A         B         C         D         E
0      4545  0.049847  0.689273  0.459255  0.925967
1  0.739994  0.665925  0.080437  0.143889  0.873782
2  0.108196  0.173969  0.949344  0.291107  0.686706
3  0.070031  0.002254  0.624236  0.486904  0.583486
4  0.967489  0.744893  0.764783  0.746854  0.725436

In [48]:
newdf.loc[[1,2],['C','D']]

          C         D
1  0.080437  0.143889
2  0.949344  0.291107

In [ ]:
newdf.loc[:,['C',"D"]] # For Rows

            C         D
0    0.689273  0.459255
1    0.080437  0.143889
2    0.949344  0.291107
3    0.624236  0.486904
4    0.764783  0.746854
..        ...       ...
329  0.596947  0.082487
330  0.391025  0.230010
331  0.600161  0.768652
332  0.586758  0.972805
333  0.455689  0.919523

[334 rows x 2 columns]

In [50]:
# for column
newdf.loc[[1,2],:]

          A         B         C         D         e
1  0.739994  0.665925  0.080437  0.143889  0.873782
2  0.108196  0.173969  0.949344  0.291107  0.686706

In [ ]:
# Complex queries
newdf.loc[(newdf['A']<0.3)]

            A         B         C         D         e
2    0.108196  0.173969  0.949344  0.291107  0.686706
3    0.070031  0.002254  0.624236  0.486904  0.583486
5    0.161596  0.458489  0.734789  0.814874  0.974828
6    0.115169  0.159287  0.496454  0.938661  0.062452
9    0.255354  0.993437  0.305269  0.442908  0.971202
..        ...       ...       ...       ...       ...
321  0.142705  0.951886  0.486304  0.559183  0.190423
326  0.229506  0.760461  0.539168  0.308576  0.693495
327    0.2021  0.471973  0.943828  0.171434  0.387302
328  0.164489  0.155751  0.499823  0.307323  0.028033
332  0.095042  0.794782  0.586758  0.972805  0.019028

[93 rows x 5 columns]

In [52]:
newdf.loc[(newdf['A']<0.3) & (newdf['C']>0.1)]

            A         B         C         D         e
2    0.108196  0.173969  0.949344  0.291107  0.686706
3    0.070031  0.002254  0.624236  0.486904  0.583486
5    0.161596  0.458489  0.734789  0.814874  0.974828
6    0.115169  0.159287  0.496454  0.938661  0.062452
9    0.255354  0.993437  0.305269  0.442908  0.971202
..        ...       ...       ...       ...       ...
321  0.142705  0.951886  0.486304  0.559183  0.190423
326  0.229506  0.760461  0.539168  0.308576  0.693495
327    0.2021  0.471973  0.943828  0.171434  0.387302
328  0.164489  0.155751  0.499823  0.307323  0.028033
332  0.095042  0.794782  0.586758  0.972805  0.019028

[84 rows x 5 columns]