 date -15/12/2025

In [2]:
import pandas as pd

In [3]:
# pip install xlrd 
# pip install openpyxl
df=pd.read_excel('weather_data.xlsx')
print(df)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [4]:
# write DF to csv
df.to_csv('new.csv')
df.to_csv('new_NoIndex.csv', index=False)

In [5]:
import pandas as pd
df=pd.read_csv('weather_data_cities.csv')
df #weather by cities

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [6]:
g=df.groupby('city')
g

In [7]:
for city,city_df in g:
    print(city)
    print(city_df)

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [12]:
for city,city_df in g:
    print(city)
    print(city_df['temperature'].min())
    print(city_df['temperature'].max())
    print(city_df['temperature'].mean())
    print(city_df['temperature'].median())
    print(city_df['temperature'].std())
    print(city_df['temperature'].describe())

mumbai
85
92
88.5
88.5
3.1091263510296048
count     4.000000
mean     88.500000
std       3.109126
min      85.000000
25%      86.500000
50%      88.500000
75%      90.500000
max      92.000000
Name: temperature, dtype: float64
new york
28
36
32.25
32.5
3.304037933599835
count     4.000000
mean     32.250000
std       3.304038
min      28.000000
25%      31.000000
50%      32.500000
75%      33.750000
max      36.000000
Name: temperature, dtype: float64
paris
42
54
47.75
47.5
5.315072906367325
count     4.000000
mean     47.750000
std       5.315073
min      42.000000
25%      44.250000
50%      47.500000
75%      51.000000
max      54.000000
Name: temperature, dtype: float64

In [10]:
# or to get specific group
g.get_group('new york')

        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny

In [13]:
print(g.describe())

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

In [14]:
import pandas as pd
india_weather=pd.DataFrame({
    "city":["mumbai","delhi","banglore"],
    "temperature":[32,45,30],
    "humidity":[80,90,98]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        90
2  banglore           30        98

In [15]:
us_weather=pd.DataFrame({
    "city":["New York","Chicago","orlando"],
    "Temperature":[22,33,24],
    "Humidity":[65,88,67]
})
us_weather

       city  Temperature  Humidity
0  New York           22        65
1   Chicago           33        88
2   orlando           24        67

In [17]:
#concate Teo dataframes
df=pd.concat([india_weather,us_weather])
df

       city  temperature  humidity  Temperature  Humidity
0    mumbai         32.0      80.0          NaN       NaN
1     delhi         45.0      90.0          NaN       NaN
2  banglore         30.0      98.0          NaN       NaN
0  New York          NaN       NaN         22.0      65.0
1   Chicago          NaN       NaN         33.0      88.0
2   orlando          NaN       NaN         24.0      67.0

In [20]:
# if you want continous index
df=pd.concat([india_weather,us_weather],ignore_index=True,axis=0)
df

       city  temperature  humidity  Temperature  Humidity
0    mumbai         32.0      80.0          NaN       NaN
1     delhi         45.0      90.0          NaN       NaN
2  banglore         30.0      98.0          NaN       NaN
3  New York          NaN       NaN         22.0      65.0
4   Chicago          NaN       NaN         33.0      88.0
5   orlando          NaN       NaN         24.0      67.0

In [21]:
# if you want continous index
df=pd.concat([india_weather,us_weather],ignore_index=True,axis=1)
df

          0   1   2         3   4   5
0    mumbai  32  80  New York  22  65
1     delhi  45  90   Chicago  33  88
2  banglore  30  98   orlando  24  67

# Merge DAtaFrames

In [22]:
temperature_df=pd.DataFrame({
    "city":["mumbai","delhi","banglore","Hydrabad"],
    "temperature":[22,33,44,22]})
temperature_dtemperature_df=pd.DataFrame({
    'city':["mumbai","Delhi","banglore","hydrabad"],
    "termperature":[32,45,30,40]
})
temperature_df

       city  temperature
0    mumbai           22
1     delhi           33
2  banglore           44
3  Hydrabad           22

In [23]:
humidity_df=pd.DataFrame({
    "city":["delhi","mumbai","banglore"],
    "humidity":[22,32,23]
})
humidity_df

       city  humidity
0     delhi        22
1    mumbai        32
2  banglore        23

In [24]:
#merge Two dataframe with out explicitly mention index
df=pd.merge(temperature_df,humidity_df,on='city')
df

       city  temperature  humidity
0    mumbai           22        32
1     delhi           33        22
2  banglore           44        23

In [25]:
    # Outer Join
df=pd.merge(temperature_df,humidity_df,on='city',how ='outer')
df

       city  temperature  humidity
0  Hydrabad           22       NaN
1  banglore           44      23.0
2     delhi           33      22.0
3    mumbai           22      32.0

# Numerical Indexing(.loc vs iloc)

In [28]:
df=pd.DataFrame([1,2,3,4,5,6,7,8,19], index=[49,48,47,46,45,1,2,3,4])
df

     0
49   1
48   2
47   3
46   4
45   5
1    6
2    7
3    8
4   19

In [29]:
df.loc[:2]

    0
49  1
48  2
47  3
46  4
45  5
1   6
2   7

In [30]:
df.iloc[:2]

    0
49  1
48  2

In [31]:
df.loc[45]

0    5
Name: 45, dtype: int64

In [32]:
df.iloc[45]

IndexError: single positional indexer is out-of-bounds